-- Запрос 1
-- SELECT NAME_TEACHER AS 'Фамилия', DOLGNOST AS 'Должность' FROM TEACHER WHERE DATA_HIRE > '1/01/2002'...

SELECT NAME_TEACHER AS 'Фамилия', DOLGNOST AS 'Должность' FROM TEACHER WHERE DATA_HIRE > '1/01/2002';