-- Запрос 16
-- SELECT Name_Kafedru, NUM_KORPUSA FROM KAFEDRA WHERE NOT (NUM_KORPUSA BETWEEN ‘1’ AND '3');...

SELECT Name_Kafedru, NUM_KORPUSA FROM KAFEDRA WHERE NOT (NUM_KORPUSA BETWEEN ‘1’ AND '3');