-- Запрос 22
-- SELECT NAME_TEACHER, DOLGNOST FROM TEACHER WHERE LOWER(NAME_TEACHER + DOLGNOST) LIKE '%o%o%o%o%o%';...

SELECT NAME_TEACHER, DOLGNOST FROM TEACHER WHERE LOWER(NAME_TEACHER + DOLGNOST) LIKE '%o%o%o%o%o%';