-- Запрос 46
-- SELECT C0UNT(DISTINCT DOLGNOST) FROM KAFEDRA d, TEACHER t WHERE d.KOD_KAFEDRU = t.KOD_KAFEDRU AND LO...

SELECT C0UNT(DISTINCT DOLGNOST) FROM KAFEDRA d, TEACHER t WHERE d.KOD_KAFEDRU = t.KOD_KAFEDRU AND LOWER(d.NAME_KAFEDRU) = 'Компьютерные системы и сети';