-- Запрос 5
-- SELECT NAME_FACULTETA FROM FACULTET WHERE NOT LOWER(NAME_FACULTETA) = 'математики и информатики';...

SELECT NAME_FACULTETA FROM FACULTET WHERE NOT LOWER(NAME_FACULTETA) = 'математики и информатики';