-- Запрос 6
-- SELECT NAME_TEACHER, DOLGNOST, Salary, Rise FROM TEACHER WHERE LOWER(DOLGNOST) ='ассистент' AND (Sal...

SELECT NAME_TEACHER, DOLGNOST, Salary, Rise FROM TEACHER WHERE LOWER(DOLGNOST) ='ассистент' AND (Salary < 550 OR Rise > 60);